- name: Create sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: narwhaledu
    instance_type: t1.micro
    security_group: narwhaledu
    image: ami-0358ce33
    region: us-west-2
  roles:
    - launch_instance

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"

  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
